### ISSUE TITLE
開発用: 座席に配置するQRコード自動生成機能の作成

### ISSUE THREAD

**Issue by a8119187** [a8119037/isfw2#20]
## 概要
1教室分のQRコードの自動生成機能を作る
どれがどれかわからなくならないように気をつけてデータを出力する。

## QRコードの中身 

usertopへのリンク + sheet_idのパラメータ

## やること

1. [x] QRコードの作成テスト
2. [x] 教室の全座席分のQRコードの作成
3. [x] 読み込みテスト

**Comment by a8119037** [comment]
QRコードの機能なんの資料参考しているか教えて欲しい！
URL貼って欲しい

**Comment by a8119187** [comment]
QRの読み取りは本家と、imageData関連で[codecamp](https://blog.codecamp.jp/programming-javascript-Imagedata)の記事参考にした。あと[ここのwiki](https://github.com/a8119037/isfw2/wiki/QR%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E8%AA%AD%E3%81%BF%E5%8F%96%E3%82%8A)に概要少しだけ書いてみた。

QRの作成は別のライブラリだから、まだどれ使うか・どれ使うのが良いのか決めてない状態〜。
先生はjquery.qrcode.jsが簡単でいいんじゃない？って言ってた。資料は[これ](https://frudens.jp/tag/jquery-qrcode-js/)とか？
使い方は[ドキュメント](https://github.com/jeromeetienne/jquery-qrcode)みた方が早いかも。

**Comment by a8119187** [comment]
ちなみに俺は出欠席のissue以外まだ手つけてないから、やる時はissueの右上のAssigneesに自分の名前登録するとわかりやすいかもー

**Comment by a8119187** [comment]
> ちなみに俺は出欠席のissue以外まだ手つけてないから、やる時はissueの右上のAssigneesに自分の名前登録するとわかりやすいかもー

あとコミットメッセージにIssueの番号 #20 つけるとコミットがissueに紐づいてここに乗るから便利かも...俺は結構やり忘れてるけど

**Comment by a8119187** [comment]
> 76f5f11002a1ece4cfe914acd9810ea386e73a55

横印刷で１枚1QRになるページを作った。
